---
LEARNING_RATE: 0.0001
BATCH_SIZE: 4
NUM_EPOCHS: 200
NUM_WORKERS: 2
IMAGE_HEIGHT: 256  # 1280 originally
IMAGE_WIDTH: 512  # 1918 originally
PIN_MEMORY: false
LOAD_MODEL: false
num_classes: 4 # Number of category
TRAIN_IMG_DIR: data/train_images/
TRAIN_MASK_DIR: data/train_masks/
VAL_IMG_DIR: data/val_images/
VAL_MASK_DIR: data/val_masks/
