---
LEARNING_RATE: 0.0001
BATCH_SIZE: 8
NUM_EPOCHS: 3
NUM_WORKERS: 1
IMAGE_HEIGHT: 160  # 1280 originally
IMAGE_WIDTH: 240  # 1918 originally
PIN_MEMORY: false
LOAD_MODEL: false
TRAIN_IMG_DIR: data/train_images/
TRAIN_MASK_DIR: data/train_masks/
VAL_IMG_DIR: data/val_images/
VAL_MASK_DIR: data/val_masks/
